### PR TITLE
Update monk package version

### LINKED ISSUE #13: Outdated monk package
It seems that this module is using an outdated version of Monk, which is causing some weird errors with dependencies. 

```
$ npm install
[...]
├─┬ botkit-storage-mongo@1.0.3 
│ └─┬ monk@1.0.1 
│   ├── UNMET PEER DEPENDENCY mongodb@~1.4
│   ├── mongoskin@1.4.13 
│   └── mpromise@0.5.1 
[...]
npm WARN mongoskin@1.4.13 requires a peer of mongodb@~1.4 but none was installed.
```

This is a bug with monk, not your app, but you're using `monk@1.0.1`, and the latest version is `monk@2.1.0`. `2.1.0` has the issue fixed (since, like, last year).

### PR DESCRIPTION
**Pull request by takouhai**
This fixes #13 , which is a simple version issue with monk.

### CODE REVIEW

**Comment by dsifford** [comment]
Can this get tagged as a semver release so I can pull it from npm?

**Comment by dsifford** [comment]
@anonrig See above. 

I have my bot on an automatic build and this is creating a giant headache. If you could tag an npm release for this it would really make my life a whole lot easier!

Thanks in advance

**Comment by anonrig** [comment]
Sorry @dsifford I don't really have the NPM permission to do that. 

@benbrown Can you bump the NPM version? Thanks.

**Comment by buritica** [comment]
hey @benbrown is there anything I can help you with to get this bumped?

**Comment by benbrown** [comment]
Sorry for the delay!  1.0.4 has been published to npm.

**Comment by buritica** [comment]
no problem, thank you so much!!

**Pull request merged**
